# Generated by Django 3.1 on 2020-09-03 11:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('daily_service', models.BooleanField(default=False)),
                ('outstanding_amount', models.FloatField()),
                ('amount_paid', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('distributer', models.CharField(blank=True, max_length=20)),
                ('size', models.CharField(blank=True, max_length=10)),
                ('weight', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('cost_price', models.FloatField(default=0)),
                ('selling_price', models.FloatField(default=1)),
                ('mfg_date', models.DateField(default=datetime.date.today)),
                ('exp_date', models.DateField()),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('total_cost', models.CharField(max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('daily_order', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.customer')),
                ('order_items', models.ManyToManyField(to='inventory.Order_Items')),
            ],
        ),
    ]
